import type { TransactionEvent } from './api-client';

// Generate events for the last 7 days
const now = new Date();
const getDate = (daysAgo: number) => {
  const date = new Date(now);
  date.setDate(date.getDate() - daysAgo);
  return date.toISOString();
};

export const WEEK_HISTORY_EVENTS: TransactionEvent[] = [
  // Day 7 - Income
  {
    timestamp: getDate(7),
    amount: 450,
    direction: 'credit',
    channel: 'UPI',
    merchant: 'Swiggy',
    category: 'income',
    source: 'mock_sms_demo',
    rawText: 'You received ₹450.00 from Swiggy via UPI',
  },
  {
    timestamp: getDate(7),
    amount: 120,
    direction: 'debit',
    channel: 'UPI',
    merchant: 'Petrol Pump',
    category: 'fuel',
    source: 'mock_sms_demo',
    rawText: 'You paid ₹120.00 to Petrol Pump via UPI',
  },
  {
    timestamp: getDate(7),
    amount: 80,
    direction: 'debit',
    channel: 'UPI',
    merchant: 'Restaurant',
    category: 'food',
    source: 'mock_sms_demo',
    rawText: 'You paid ₹80.00 to Restaurant via UPI',
  },
  // Day 6
  {
    timestamp: getDate(6),
    amount: 380,
    direction: 'credit',
    channel: 'UPI',
    merchant: 'Swiggy',
    category: 'income',
    source: 'mock_sms_demo',
    rawText: 'You received ₹380.00 from Swiggy via UPI',
  },
  {
    timestamp: getDate(6),
    amount: 150,
    direction: 'debit',
    channel: 'UPI',
    merchant: 'Petrol Pump',
    category: 'fuel',
    source: 'mock_sms_demo',
    rawText: 'You paid ₹150.00 to Petrol Pump via UPI',
  },
  {
    timestamp: getDate(6),
    amount: 100,
    direction: 'debit',
    channel: 'UPI',
    merchant: 'Grocery Store',
    category: 'food',
    source: 'mock_sms_demo',
    rawText: 'You paid ₹100.00 to Grocery Store via UPI',
  },
  // Day 5
  {
    timestamp: getDate(5),
    amount: 520,
    direction: 'credit',
    channel: 'UPI',
    merchant: 'Swiggy',
    category: 'income',
    source: 'mock_sms_demo',
    rawText: 'You received ₹520.00 from Swiggy via UPI',
  },
  {
    timestamp: getDate(5),
    amount: 110,
    direction: 'debit',
    channel: 'UPI',
    merchant: 'Petrol Pump',
    category: 'fuel',
    source: 'mock_sms_demo',
    rawText: 'You paid ₹110.00 to Petrol Pump via UPI',
  },
  {
    timestamp: getDate(5),
    amount: 90,
    direction: 'debit',
    channel: 'UPI',
    merchant: 'Restaurant',
    category: 'food',
    source: 'mock_sms_demo',
    rawText: 'You paid ₹90.00 to Restaurant via UPI',
  },
  // Day 4
  {
    timestamp: getDate(4),
    amount: 410,
    direction: 'credit',
    channel: 'UPI',
    merchant: 'Swiggy',
    category: 'income',
    source: 'mock_sms_demo',
    rawText: 'You received ₹410.00 from Swiggy via UPI',
  },
  {
    timestamp: getDate(4),
    amount: 130,
    direction: 'debit',
    channel: 'UPI',
    merchant: 'Petrol Pump',
    category: 'fuel',
    source: 'mock_sms_demo',
    rawText: 'You paid ₹130.00 to Petrol Pump via UPI',
  },
  {
    timestamp: getDate(4),
    amount: 70,
    direction: 'debit',
    channel: 'UPI',
    merchant: 'Restaurant',
    category: 'food',
    source: 'mock_sms_demo',
    rawText: 'You paid ₹70.00 to Restaurant via UPI',
  },
  // Day 3
  {
    timestamp: getDate(3),
    amount: 480,
    direction: 'credit',
    channel: 'UPI',
    merchant: 'Swiggy',
    category: 'income',
    source: 'mock_sms_demo',
    rawText: 'You received ₹480.00 from Swiggy via UPI',
  },
  {
    timestamp: getDate(3),
    amount: 140,
    direction: 'debit',
    channel: 'UPI',
    merchant: 'Petrol Pump',
    category: 'fuel',
    source: 'mock_sms_demo',
    rawText: 'You paid ₹140.00 to Petrol Pump via UPI',
  },
  {
    timestamp: getDate(3),
    amount: 85,
    direction: 'debit',
    channel: 'UPI',
    merchant: 'Restaurant',
    category: 'food',
    source: 'mock_sms_demo',
    rawText: 'You paid ₹85.00 to Restaurant via UPI',
  },
  // Day 2
  {
    timestamp: getDate(2),
    amount: 360,
    direction: 'credit',
    channel: 'UPI',
    merchant: 'Swiggy',
    category: 'income',
    source: 'mock_sms_demo',
    rawText: 'You received ₹360.00 from Swiggy via UPI',
  },
  {
    timestamp: getDate(2),
    amount: 125,
    direction: 'debit',
    channel: 'UPI',
    merchant: 'Petrol Pump',
    category: 'fuel',
    source: 'mock_sms_demo',
    rawText: 'You paid ₹125.00 to Petrol Pump via UPI',
  },
  {
    timestamp: getDate(2),
    amount: 95,
    direction: 'debit',
    channel: 'UPI',
    merchant: 'Grocery Store',
    category: 'food',
    source: 'mock_sms_demo',
    rawText: 'You paid ₹95.00 to Grocery Store via UPI',
  },
  // Day 1
  {
    timestamp: getDate(1),
    amount: 440,
    direction: 'credit',
    channel: 'UPI',
    merchant: 'Swiggy',
    category: 'income',
    source: 'mock_sms_demo',
    rawText: 'You received ₹440.00 from Swiggy via UPI',
  },
  {
    timestamp: getDate(1),
    amount: 115,
    direction: 'debit',
    channel: 'UPI',
    merchant: 'Petrol Pump',
    category: 'fuel',
    source: 'mock_sms_demo',
    rawText: 'You paid ₹115.00 to Petrol Pump via UPI',
  },
  {
    timestamp: getDate(1),
    amount: 75,
    direction: 'debit',
    channel: 'UPI',
    merchant: 'Restaurant',
    category: 'food',
    source: 'mock_sms_demo',
    rawText: 'You paid ₹75.00 to Restaurant via UPI',
  },
];

export const BIG_REPAIR_EVENT: TransactionEvent[] = [
  {
    timestamp: new Date().toISOString(),
    amount: 1800,
    direction: 'debit',
    channel: 'UPI',
    merchant: 'Bike Repair Shop',
    category: 'other',
    source: 'mock_sms_demo',
    rawText: 'You paid ₹1800.00 to Bike Repair Shop via UPI',
  },
];

